schema 
    : value
    ;

value
    : object
    | array
    | generator
    | range
    | STRING
    ;

object
    : '{' pair (COMMA pair)* '}'
    ;

pair
    : STRING COLON value
    ;

array
    : '[' range COMMA value (COMMA value)* ']'
    | '[' value (COMMA value)* ']'
    ;

generator
    : [a-zA-Z][a-zA-Z]*
    ;

range
    : '(' NATURAL COMMA NATURAL ')'
    | '(' NATURAL ')'
    ;

COMMA
    : ','
    ;

COLON
    : ':'
    ;

STRING
    : '"' (UNICODE)* '"'
    ;

HEX
    : [0-9a-fA-F]
    ;

UNICODE
    : '\\u' HEX HEX HEX HEX
    ;

NATURAL
    : [1-9][0-9]*
    | [0-9]
    ;